version: '3.8'
services:
 petclinic:
   image: tstimage
   build:   
     context: .
     target: stage2
     dockerfile: Dockerfile.tst
   ports:
     - 8000:8000
     - 8080:8080
   environment:
     - SERVER_PORT=8080
     - MYSQL_URL=jdbc:mysql://mysqlserver/petclinic
   volumes:
     - ./:/app   
      